//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MOD95.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_AUDIOSETUP                  101
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR                     128
#define IDR_MODULETYPE                  129
#define IDC_COMBO1                      1000
#define IDC_EDIT1                       1001
#define IDC_CHECK1                      1002
#define ID_VIDEO_PLAY                   32771
#define ID_VIDEO_STOP                   32772
#define ID_VIDEO_PREV                   32773
#define ID_VIDEO_NEXT                   32774
#define ID_AUDIOSETUP                   32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
